services:
  postgres:
    image: postgres:16
    container_name: agenda_local_postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "MCP_agenda"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db init:/docker-entrypoint-initdb.d  # Mount SQL init script
      - ./csv:/csv  # mount csv folder

volumes:
  postgres_data:
